version: '3'
services:
  web:
    image: server-image
    deploy:
      replicas: 3
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      - "mongo"
  mongo:
      image: "mongo" 
      ports:
       - 27017:27017
      networks:
        - my_network
      volumes:
      - db-data:/data/db

networks:
    my_network:

volumes:
  db-data:
